name: 3.multi-jobs-using-needs
on: 
  workflow_dispatch: 
jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job-1"
  job-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job-2"
  job-3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is job-3"
  job-4:
    runs-on: ubuntu-latest
    needs:
    - job-1
    - job-2
    - job-3
    steps:
       - run: echo "this is job-4 4th jobs"
